name: edge_demo
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - numpy
  - opencv
  - tflite-runtime       # tflite 인터프리터 (TensorFlow 전체 패키지 대신)
  - pip:
      - pycoral          # Edge TPU delegate
      - pillow
